### PR TITLE
Add RocksDB support to KVs

### PR DESCRIPTION
**Pull request by atoulme**
Also have KVs implement their own CoroutineScope, similar to DiscoveryService, so we don't use GlobalScope in async methods.

### CODE REVIEW

**Comment by cleishm** [comment]
So I purposefully didn’t have KV implement the CoroutineScope, as the cancellation scope for those async methods is outside the lifetime of the service.

**Comment by cleishm** [comment]
But agree that using GlobalScope is wrong. It should ideally be the scope of the caller.

**Comment by atoulme** [comment]
Hard to get a context in Java though?

**Comment by atoulme** [comment]
OK, I have scaled back the changes back to just adding RocksDB. Should be good to go.

**Comment by cleishm** [comment]
> Hard to get a context in Java though?
 
Right. Hence I went with global scope. If you want cancellation scoping, you should be in Kotlin using the suspend methods anyway.

**Pull request merged**
